export type LanguageCode = 
  | 'en' 
  | 'hi' 
  | 'bn' 
  | 'te' 
  | 'mr' 
  | 'ta' 
  | 'gu' 
  | 'kn' 
  | 'or' 
  | 'ml';

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  nativeName: string;
  flagLetter: string;
}

export const INDIAN_LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', nativeName: 'English', flagLetter: 'EN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flagLetter: 'हि' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flagLetter: 'বা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flagLetter: 'తె' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flagLetter: 'म' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flagLetter: 'த' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flagLetter: 'ગુ' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flagLetter: 'ಕ' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flagLetter: 'ଓ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flagLetter: 'മ' },
];

export const UI_TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav & General
    dashboard: 'Dashboard',
    mock_tests: 'Mock Tests',
    analytics: 'Analytics',
    notifications: 'Exam Calendar',
    ebooks: 'Study Notes & PDFs',
    teach_with_us: 'Teach With Us',
    admin_portal: 'Admin Portal',
    login_with_google: 'Student Sign In',
    logout: 'Sign Out',
    
    // TCS CBT Header
    tcs_cbt_title: 'TCS iON Assessment Engine',
    system_no: 'System Name: C-004',
    candidate_name: 'Candidate Name',
    roll_no: 'Roll Number',
    time_left: 'Time Left',
    view_instructions: 'Instructions',
    view_question_paper: 'Question Paper',
    attached_pdf: 'Attached PDF Note',
    language: 'Language',
    font_size: 'Font Size',
    high_contrast: 'High Contrast',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',

    // TCS Status Legend
    legend_not_visited: 'Not Visited',
    legend_not_answered: 'Not Answered',
    legend_answered: 'Answered',
    legend_marked: 'Marked for Review',
    legend_answered_marked: 'Answered & Marked for Review (will be evaluated)',
    question_palette: 'Question Palette',

    // TCS Question & Action Controls
    question_no: 'Question No.',
    marks: 'Marks',
    negative_marks: 'Negative',
    save_and_next: 'Save & Next',
    clear_response: 'Clear Response',
    mark_for_review_next: 'Mark for Review & Next',
    submit_exam: 'Submit Test',
    previous: 'Previous',
    next: 'Next',
    
    // Exam Section
    choose_target_exam: 'Choose Target Exam:',
    targeting: 'Targeting',
    official_mocks: 'Official Mocks & Study Lessons for',
    available_tests: 'Tests Available',
    start_test: 'Start Test',
    unlock_pass: '7-Day Free Trial',
    free_test: 'Free Test',
    custom_segment: '10-50 Qs',
    read_pdf_first: 'Read PDF First',
    all_types: 'All Types',
    chapterwise: 'Chapterwise',
    full_length: 'Full Length Mocks',
    sectional: 'Section-wise',
    search_placeholder: 'Search questions, lessons, topics...',
    pass_status: 'Pass Status',
    pass_active: 'Pass Active',
    free_trial: 'Free Trial',
    extend_pass: 'Extend Pass (365 Days)',
    unlock_full_access: 'Start 7-Day Free Trial',
    mandatory_quote: '1 lakh+ students have already cleared their exams using this platform for last 5 years across India',
    
    // Dialogs & Modals
    confirm_submit_title: 'Submit Examination?',
    confirm_submit_msg: 'Are you sure you want to finish and submit this test? You will see instant performance analytics.',
    cancel: 'Cancel',
    confirm_submit_btn: 'Yes, Submit Test',
    exam_summary: 'Exam Summary',
    total_questions: 'Total Questions',
  },
  hi: {
    // Nav & General
    dashboard: 'डैशबोर्ड',
    mock_tests: 'मॉक टेस्ट',
    analytics: 'प्रदर्शन विश्लेषण',
    notifications: 'परीक्षा कैलेंडर',
    ebooks: 'स्टडी नोट्स और पीडीएफ',
    teach_with_us: 'हमारे साथ पढ़ाएं',
    admin_portal: 'एडमिन पोर्टल',
    login_with_google: 'छात्र लॉगिन करें',
    logout: 'लॉग आउट',

    // TCS CBT Header
    tcs_cbt_title: 'TCS iON परीक्षा प्रणाली',
    system_no: 'सिस्टम नंबर: C-004',
    candidate_name: 'अभ्यर्थी का नाम',
    roll_no: 'अनुक्रमांक (Roll No.)',
    time_left: 'शेष समय',
    view_instructions: 'निर्देश',
    view_question_paper: 'प्रश्न पत्र',
    attached_pdf: 'संलग्न पीडीएफ नोट्स',
    language: 'भाषा चुनें',
    font_size: 'फ़ॉन्ट आकार',
    high_contrast: 'उच्च कंट्रास्ट',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',

    // TCS Status Legend
    legend_not_visited: 'अभी तक नहीं देखा',
    legend_not_answered: 'उत्तर नहीं दिया',
    legend_answered: 'उत्तर दिया गया',
    legend_marked: 'समीक्षा के लिए चिह्नित',
    legend_answered_marked: 'उत्तर दिया और समीक्षा के लिए चिह्नित (मूल्यांकन होगा)',
    question_palette: 'प्रश्न पैलेट',

    // TCS Question & Action Controls
    question_no: 'प्रश्न संख्या',
    marks: 'अंक',
    negative_marks: 'नकारात्मक अंक',
    save_and_next: 'सुरक्षित करें और अगला',
    clear_response: 'उत्तर साफ़ करें',
    mark_for_review_next: 'समीक्षा के लिए चिह्नित करें और अगला',
    submit_exam: 'परीक्षा जमा करें',
    previous: 'पिछला',
    next: 'अगला',

    // Exam Section
    choose_target_exam: 'लक्ष्य परीक्षा चुनें:',
    targeting: 'लक्ष्य परीक्षा',
    official_mocks: 'के लिए आधिकारिक मॉक और अध्ययन पाठ',
    available_tests: 'उपलब्ध टेस्ट',
    start_test: 'टेस्ट शुरू करें',
    unlock_pass: '7-दिन फ्री ट्रायल',
    free_test: 'निःशुल्क टेस्ट',
    custom_segment: '10-50 प्रश्न',
    read_pdf_first: 'पहले पीडीएफ पढ़ें',
    all_types: 'सभी प्रकार',
    chapterwise: 'अध्याय-वार',
    full_length: 'संपूर्ण मॉक टेस्ट',
    sectional: 'अनुभाग-वार',
    search_placeholder: 'प्रश्न, पाठ, विषय खोजें...',
    pass_status: 'पास स्थिति',
    pass_active: 'पास सक्रिय है',
    free_trial: 'फ्री ट्रायल',
    extend_pass: 'पास बढ़ाएं (365 दिन)',
    unlock_full_access: '7-दिन का फ्री ट्रायल शुरू करें',
    mandatory_quote: 'भारत भर में पिछले 5 वर्षों में 1 लाख से अधिक छात्रों ने इस मंच से अपनी परीक्षाएं उत्तीर्ण की हैं',

    // Dialogs & Modals
    confirm_submit_title: 'क्या आप परीक्षा जमा करना चाहते हैं?',
    confirm_submit_msg: 'क्या आप वाकई इस टेस्ट को समाप्त और जमा करना चाहते हैं? तुरंत परिणाम और विश्लेषण दिखाई देगा।',
    cancel: 'रद्द करें',
    confirm_submit_btn: 'हाँ, परीक्षा जमा करें',
    exam_summary: 'परीक्षा सारांश',
    total_questions: 'कुल प्रश्न',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    mock_tests: 'মক টেস্ট',
    analytics: 'ফলাফল বিশ্লেষণ',
    notifications: 'পরীক্ষার সময়সূচী',
    ebooks: 'স্টাডি নোট ও পিডিএফ',
    teach_with_us: 'আমাদের সাথে শিক্ষকতা করুন',
    admin_portal: 'অ্যাডমিন পোর্টাল',
    login_with_google: 'স্টুডেন্ট লগইন',
    logout: 'লগআউট',
    tcs_cbt_title: 'TCS iON পরীক্ষা ব্যবস্থা',
    system_no: 'সিস্টেম নং: C-004',
    candidate_name: 'পরীক্ষার্থীর নাম',
    roll_no: 'রোল নম্বর',
    time_left: 'বাকি সময়',
    view_instructions: 'নির্দেশাবলী',
    view_question_paper: 'প্রশ্নপত্র',
    attached_pdf: 'সংযুক্ত পিডিএফ নোট',
    language: 'ভাষা নির্বাচন',
    font_size: 'ফন্ট সাইজ',
    high_contrast: 'উচ্চ কনট্রাস্ট',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',
    legend_not_visited: 'পরিদর্শন করা হয়নি',
    legend_not_answered: 'উত্তর দেওয়া হয়নি',
    legend_answered: 'উত্তর দেওয়া হয়েছে',
    legend_marked: 'পর্যালোচনার জন্য চিহ্নিত',
    legend_answered_marked: 'উত্তর দিয়ে চিহ্নিত (মূল্যায়ন করা হবে)',
    question_palette: 'প্রশ্ন প্যালেট',
    question_no: 'প্রশ্ন নং',
    marks: 'নম্বর',
    negative_marks: 'নেগেটিভ',
    save_and_next: 'সংরক্ষণ ও পরবর্তী',
    clear_response: 'উত্তর মুছুন',
    mark_for_review_next: 'পর্যালোচনার জন্য চিহ্নিত ও পরবর্তী',
    submit_exam: 'পরীক্ষা জমা দিন',
    previous: 'পূর্ববর্তী',
    next: 'পরবর্তী',
    choose_target_exam: 'টার্গেট পরীক্ষা বাছুন:',
    targeting: 'লক্ষ্য পরীক্ষা',
    official_mocks: 'এর জন্য অফিসিয়াল মক টেস্ট ও পাঠ',
    available_tests: 'উপলব্ধ টেস্ট',
    start_test: 'টেস্ট শুরু করুন',
    unlock_pass: '₹২ এ আনলক করুন',
    free_test: 'ফ্রি টেস্ট',
    custom_segment: '১০-৫০টি প্রশ্ন',
    read_pdf_first: 'প্রথমে পিডিএফ পড়ুন',
    all_types: 'সকল ধরণ',
    chapterwise: 'অধ্যায়ভিত্তিক',
    full_length: 'সম্পূর্ণ মক টেস্ট',
    sectional: 'বিভাগভিত্তিক',
    search_placeholder: 'প্রশ্ন, পাঠ ও বিষয় অনুসন্ধান করুন...',
    pass_status: 'পাস স্ট্যাটাস',
    pass_active: 'পাস সক্রিয়',
    free_trial: 'ফ্রি ট্রায়াল',
    extend_pass: 'পাস বৃদ্ধি করুন (৩৬৫ দিন)',
    unlock_full_access: '₹২ এ সম্পূর্ণ অ্যাক্সেস নিন',
    mandatory_quote: 'গত ৫ বছরে ভারতজুড়ে ১ লাখেরও বেশি ছাত্রছাত্রী এই প্ল্যাটফর্ম ব্যবহার করে তাদের পরীক্ষা উত্তীর্ণ হয়েছে',
    confirm_submit_title: 'পরীক্ষা জমা দিতে চান?',
    confirm_submit_msg: 'আপনি কি নিশ্চিত যে এই মক টেস্টটি শেষ করে জমা দিতে চান?',
    cancel: 'বাতিল',
    confirm_submit_btn: 'হ্যাঁ, জমা দিন',
    exam_summary: 'পরীক্ষার সারাংশ',
    total_questions: 'মোট প্রশ্ন',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    mock_tests: 'మాక్ టెస్ట్‌లు',
    analytics: 'పనితీరు విశ్లేషణ',
    notifications: 'పరీక్షా క్యాలెండర్',
    ebooks: 'స్టడీ నోట్స్ & పిడిఎఫ్',
    teach_with_us: 'మాతో బోధించండి',
    admin_portal: 'అడ్మిన్ పోర్టల్',
    login_with_google: 'స్టూడెంట్ లాగిన్',
    logout: 'లాగౌట్',
    tcs_cbt_title: 'TCS iON పరీక్షా వ్యవస్థ',
    system_no: 'సిస్టమ్ సంఖ్య: C-004',
    candidate_name: 'అభ్యర్థి పేరు',
    roll_no: 'రోల్ నంబర్',
    time_left: 'మిగిలిన సమయం',
    view_instructions: 'సూచనలు',
    view_question_paper: 'ప్రశ్నాపత్రం',
    attached_pdf: 'జతచేసిన పిడిఎఫ్ నోట్',
    language: 'భాష ఎంచుకోండి',
    font_size: 'ఫాంట్ పరిమాణం',
    high_contrast: 'హై కాంట్రాస్ట్',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',
    legend_not_visited: 'సందర్శించలేదు',
    legend_not_answered: 'సమాధానం ఇవ్వలేదు',
    legend_answered: 'సమాధానం ఇచ్చారు',
    legend_marked: 'సమీక్ష కోసం గుర్తించబడింది',
    legend_answered_marked: 'సమాధానం ఇచ్చి సమీక్ష కోసం గుర్తించారు (మూల్యాంకనం చేయబడుతుంది)',
    question_palette: 'ప్రశ్నల ప్యాలెట్',
    question_no: 'ప్రశ్న సంఖ్య',
    marks: 'మార్కులు',
    negative_marks: 'నెగటివ్ మార్కులు',
    save_and_next: 'సేవ్ చేసి ముందుకు వెళ్ళండి',
    clear_response: 'సమాధానాన్ని తీసివేయండి',
    mark_for_review_next: 'సమీక్షకు గుర్తించి ముందుకు వెళ్ళండి',
    submit_exam: 'పరీక్షను సమర్పించండి',
    previous: 'మునుపటి',
    next: 'తరువాత',
    choose_target_exam: 'లక్ష్య పరీక్షను ఎంచుకోండి:',
    targeting: 'లక్ష్య పరీక్ష',
    official_mocks: 'కోసం అధికారిక మాక్ టెస్ట్‌లు',
    available_tests: 'అందుబాటులో ఉన్న టెస్ట్‌లు',
    start_test: 'టెస్ట్ ప్రారంభించండి',
    unlock_pass: '₹2 తో అన్‌లాక్ చేయండి',
    free_test: 'ఉచిత టెస్ట్',
    custom_segment: '10-50 ప్రశ్నలు',
    read_pdf_first: 'ముందుగా పిడిఎఫ్ చదవండి',
    all_types: 'అన్ని రకాలు',
    chapterwise: 'అధ్యాయాల వారీగా',
    full_length: 'పూర్తి స్థాయి మాక్స్',
    sectional: 'విభాగాల వారీగా',
    search_placeholder: 'ప్రశ్నలు, అంశాలను శోధించండి...',
    pass_status: 'పాస్ స్థితి',
    pass_active: 'పాస్ సక్రియంగా ఉంది',
    free_trial: 'ఉచిత ట్రయల్',
    extend_pass: 'పాస్ పొడిగించండి (365 రోజులు)',
    unlock_full_access: '₹2 తో పూర్తి యాక్సెస్ పొందండి',
    mandatory_quote: 'గత 5 సంవత్సరాలలో భారతదేశవ్యాప్తంగా 1 లక్షకు పైగా విద్యార్థులు ఈ ప్లాట్‌ఫారమ్ ద్వారా విజయం సాధించారు',
    confirm_submit_title: 'పరీక్షను సమర్పించాలా?',
    confirm_submit_msg: 'మీరు ఖచ్చితంగా పరీక్షను సమర్పించాలనుకుంటున్నారా?',
    cancel: 'రద్దు చేయండి',
    confirm_submit_btn: 'అవును, సమర్పించండి',
    exam_summary: 'పరీక్ష సారాంశం',
    total_questions: 'మొత్తం ప్రశ్నలు',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    mock_tests: 'मॉक टेस्ट्स',
    analytics: 'कामगिरी विश्लेषण',
    notifications: 'परीक्षा दिनदर्शिका',
    ebooks: 'अभ्यास नोट्स आणि पीडीएफ',
    teach_with_us: 'आमच्यासोबत शिकवा',
    admin_portal: 'प्रशासक पोर्टल',
    login_with_google: 'विद्यार्थी लॉगिन',
    logout: 'लॉगआउट',
    tcs_cbt_title: 'TCS iON परीक्षा प्रणाली',
    system_no: 'प्रणाली क्रमांक: C-004',
    candidate_name: 'उमेदवाराचे नाव',
    roll_no: 'रोल नंबर',
    time_left: 'उरलेला वेळ',
    view_instructions: 'सूचना',
    view_question_paper: 'प्रश्नपत्रिका',
    attached_pdf: 'जोडलेली पीडीएफ नोंद',
    language: 'भाषा निवडा',
    font_size: 'फॉन्ट आकार',
    high_contrast: 'हाय कॉन्ट्रास्ट',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',
    legend_not_visited: 'भेट दिली नाही',
    legend_not_answered: 'उत्तर दिले नाही',
    legend_answered: 'उत्तर दिले',
    legend_marked: 'पुनरावलोकनासाठी चिन्हांकित',
    legend_answered_marked: 'उत्तर दिले आणि पुनरावलोकनासाठी चिन्हांकित (मूल्यांकन केले जाईल)',
    question_palette: 'प्रश्न पॅलेट',
    question_no: 'प्रश्न क्र.',
    marks: 'गुण',
    negative_marks: 'नकारात्मक गुण',
    save_and_next: 'जतन करा आणि पुढे जा',
    clear_response: 'प्रतिसाद साफ करा',
    mark_for_review_next: 'पुनरावलोकनासाठी चिन्हांकित करा आणि पुढे जा',
    submit_exam: 'परीक्षा सबमिट करा',
    previous: 'मागे',
    next: 'पुढे',
    choose_target_exam: 'लक्ष्य परीक्षा निवडा:',
    targeting: 'लक्ष्य परीक्षा',
    official_mocks: 'साठी अधिकृत मॉक टेस्ट',
    available_tests: 'उपलब्ध टेस्ट',
    start_test: 'टेस्ट सुरू करा',
    unlock_pass: '₹२ मध्ये अनलॉक करा',
    free_test: 'मोफत टेस्ट',
    custom_segment: '१०-५० प्रश्न',
    read_pdf_first: 'प्रथम पीडीएफ वाचा',
    all_types: 'सर्व प्रकार',
    chapterwise: 'प्रकरणानुसार',
    full_length: 'संपूर्ण मॉक टेस्ट',
    sectional: 'विभागानुसार',
    search_placeholder: 'प्रश्न, विषय शोधा...',
    pass_status: 'पास स्थिती',
    pass_active: 'पास सक्रिय',
    free_trial: 'मोफत चाचणी',
    extend_pass: 'पास वाढवा (३६५ दिवस)',
    unlock_full_access: '₹२ मध्ये पूर्ण प्रवेश मिळवा',
    mandatory_quote: 'भारतात गेल्या ५ वर्षांत १ लाखांहून अधिक विद्यार्थ्यांनी या मंचावरून यश मिळवले आहे',
    confirm_submit_title: 'परीक्षा सबमिट करायची आहे का?',
    confirm_submit_msg: 'तुम्हाला खात्री आहे की तुम्ही परीक्षा पूर्ण करू इच्छिता?',
    cancel: 'रद्द करा',
    confirm_submit_btn: 'होय, सबमिट करा',
    exam_summary: 'परीक्षा सारांश',
    total_questions: 'एकूण प्रश्न',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    mock_tests: 'மாதிரித் தேர்வுகள்',
    analytics: 'செயல்திறன் பகுப்பாய்வு',
    notifications: 'தேர்வு நாட்காட்டி',
    ebooks: 'பாடக் குறிப்புகள் & PDF',
    teach_with_us: 'எங்களுடன் கற்பிக்கவும்',
    admin_portal: 'நிர்வாக போர்டல்',
    login_with_google: 'மாணவர் உள்நுழைவு',
    logout: 'வெளியேறு',
    tcs_cbt_title: 'TCS iON தேர்வு தளம்',
    system_no: 'கணினி எண்: C-004',
    candidate_name: 'தேர்வர் பெயர்',
    roll_no: 'பதிவு எண்',
    time_left: 'மீதமுள்ள நேரம்',
    view_instructions: 'வழிமுறைகள்',
    view_question_paper: 'வினாத்தாள்',
    attached_pdf: 'இணைக்கப்பட்ட PDF குறிப்பு',
    language: 'மொழியைத் தேர்வுசெய்க',
    font_size: 'எழுத்து அளவு',
    high_contrast: 'உயர் மாறுபாடு',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',
    legend_not_visited: 'பார்க்கவில்லை',
    legend_not_answered: 'பதிலளிக்கப்படவில்லை',
    legend_answered: 'பதிலளிக்கப்பட்டது',
    legend_marked: 'மறுஆய்வுக்குக் குறிக்கப்பட்டது',
    legend_answered_marked: 'பதிலளிக்கப்பட்டு மறுஆய்வுக்குக் குறிக்கப்பட்டது (மதிப்பீடு செய்யப்படும்)',
    question_palette: 'கேள்வி பலகம்',
    question_no: 'கேள்வி எண்',
    marks: 'மதிப்பெண்கள்',
    negative_marks: 'எதிர்மறை மதிப்பெண்',
    save_and_next: 'சேமித்து அடுத்து செல்க',
    clear_response: 'பதிலை அழிக்கவும்',
    mark_for_review_next: 'மறுஆய்வுக்குக் குறித்து அடுத்து செல்க',
    submit_exam: 'தேர்வைச் சமர்ப்பிக்கவும்',
    previous: 'முந்தைய',
    next: 'அடுத்தது',
    choose_target_exam: 'இலக்குத் தேர்வைத் தேர்வுசெய்க:',
    targeting: 'இலக்குத் தேர்வு',
    official_mocks: 'க்கான அதிகாரப்பூர்வ மாதிரி தேர்வுகள்',
    available_tests: 'உள்ள தேர்வுகள்',
    start_test: 'தேர்வைத் தொடங்கு',
    unlock_pass: '₹2 இல் திறக்கவும்',
    free_test: 'இலவசத் தேர்வு',
    custom_segment: '10-50 கேள்விகள்',
    read_pdf_first: 'முதலில் PDF ஐப் படிக்கவும்',
    all_types: 'அனைத்து வகைகள்',
    chapterwise: 'அத்தியாயம் வாரியாக',
    full_length: 'முழு மாதிரித் தேர்வுகள்',
    sectional: 'பிரிவு வாரியாக',
    search_placeholder: 'கேள்விகள், தலைப்புகளைத் தேடுங்கள்...',
    pass_status: 'பாஸ் நிலை',
    pass_active: 'பாஸ் செயலில் உள்ளது',
    free_trial: 'இலவச சோதனை',
    extend_pass: 'பாஸை நீட்டிக்கவும் (365 நாட்கள்)',
    unlock_full_access: '₹2 இல் முழு அணுகல் பெறுக',
    mandatory_quote: 'கடந்த 5 ஆண்டுகளில் இந்தியா முழுவதும் 1 லட்சத்திற்கும் மேற்பட்ட மாணவர்கள் இந்த தளம் மூலம் தேர்ச்சி பெற்றுள்ளனர்',
    confirm_submit_title: 'தேர்வைச் சமர்ப்பிக்கவா?',
    confirm_submit_msg: 'நிச்சயமாக நீங்கள் தேர்வைச் சமர்ப்பிக்க விரும்புகிறீர்களா?',
    cancel: 'ரத்து செய்',
    confirm_submit_btn: 'ஆம், சமர்ப்பி',
    exam_summary: 'தேர்வுச் சுருக்கம்',
    total_questions: 'மொத்தக் கேள்விகள்',
  },
  gu: {
    dashboard: 'ડેશબોર્ડ',
    mock_tests: 'મોક ટેસ્ટ',
    analytics: 'પરફોર્મન્સ એનાલિટિક્સ',
    notifications: 'પરીક્ષા કેલેન્ડર',
    ebooks: 'અભ્યાસ નોટ્સ અને પીડીએફ',
    teach_with_us: 'અમારી સાથે ભણાવો',
    admin_portal: 'એડમિન પોર્ટલ',
    login_with_google: 'વિદ્યાર્થી સાઇન ઇન',
    logout: 'લૉગઆઉટ',
    tcs_cbt_title: 'TCS iON પરીક્ષા સિસ્ટમ',
    system_no: 'સિસ્ટમ નંબર: C-004',
    candidate_name: 'ઉમેદવારનું નામ',
    roll_no: 'રોલ નંબર',
    time_left: 'બાકી સમય',
    view_instructions: 'સૂચનાઓ',
    view_question_paper: 'પ્રશ્નપત્ર',
    attached_pdf: 'જોડાયેલ પીડીએફ નોંધ',
    language: 'ભાષા પસંદ કરો',
    font_size: 'ફોન્ટ સાઇઝ',
    high_contrast: 'હાઇ કોન્ટ્રાસ્ટ',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',
    legend_not_visited: 'મુલાકાત લીધી નથી',
    legend_not_answered: 'જવાબ આપ્યો નથી',
    legend_answered: 'જવાબ આપેલ છે',
    legend_marked: 'સમીક્ષા માટે ચિહ્નિત',
    legend_answered_marked: 'જવાબ આપ્યો અને સમીક્ષા માટે ચિહ્નિત (મૂલ્યાંકન થશે)',
    question_palette: 'પ્રશ્ન પેલેટ',
    question_no: 'પ્રશ્ન ક્ર.',
    marks: 'ગુણ',
    negative_marks: 'નકારાત્મક ગુણ',
    save_and_next: 'સાચવો અને આગળ વધો',
    clear_response: 'જવાબ સાફ કરો',
    mark_for_review_next: 'સમીક્ષા માટે માર્ક કરો અને આગળ વધો',
    submit_exam: 'પરીક્ષા સબમિટ કરો',
    previous: 'પાછળ',
    next: 'આગળ',
    choose_target_exam: 'લક્ષ્ય પરીક્ષા પસંદ કરો:',
    targeting: 'લક્ષ્ય પરીક્ષા',
    official_mocks: 'માટે અધિકૃત મોક ટેસ્ટ',
    available_tests: 'ઉપલબ્ધ ટેસ્ટ',
    start_test: 'ટેસ્ટ શરૂ કરો',
    unlock_pass: '₹2 માં અનલૉક કરો',
    free_test: 'મફત ટેસ્ટ',
    custom_segment: '10-50 પ્રશ્નો',
    read_pdf_first: 'પ્રથમ પીડીએફ વાંચો',
    all_types: 'બધા પ્રકારો',
    chapterwise: 'પ્રકરણવાર',
    full_length: 'સંપૂર્ણ મોક ટેસ્ટ',
    sectional: 'વિભાગવાર',
    search_placeholder: 'પ્રશ્નો, વિષયો શોધો...',
    pass_status: 'પાસ સ્થિતિ',
    pass_active: 'પાસ સક્રિય છે',
    free_trial: 'મફત ટ્રાયલ',
    extend_pass: 'પાસ લંબાવો (365 દિવસ)',
    unlock_full_access: '₹2 માં સંપૂર્ણ એક્સેસ મેળવો',
    mandatory_quote: 'છેલ્લા 5 વર્ષમાં સમગ્ર ભારતમાં 1 લાખથી વધુ વિદ્યાર્થીઓએ આ પ્લેટફોર્મ પરથી પરીક્ષા પાસ કરી છે',
    confirm_submit_title: 'શું પરીક્ષા સબમિટ કરવી છે?',
    confirm_submit_msg: 'શું તમે ખરેખર પરીક્ષા પૂર્ણ કરવા માંગો છો?',
    cancel: 'રદ કરો',
    confirm_submit_btn: 'હા, સબમિટ કરો',
    exam_summary: 'પરીક્ષા સારાંશ',
    total_questions: 'કુલ પ્રશ્નો',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    mock_tests: 'ಅಣಕು ಪರೀಕ್ಷೆಗಳು',
    analytics: 'ಕಾರ್ಯಕ್ಷಮತೆಯ ವಿಶ್ಲೇಷಣೆ',
    notifications: 'ಪರೀಕ್ಷಾ ಕ್ಯಾಲೆಂಡರ್',
    ebooks: 'ಸ್ಟಡಿ ನೋಟ್ಸ್ & ಪಿಡಿಎಫ್',
    teach_with_us: 'ನಮ್ಮೊಂದಿಗೆ ಬೋಧಿಸಿ',
    admin_portal: 'ನಿರ್ವಾಹಕ ಪೋರ್ಟಲ್',
    login_with_google: 'ವಿದ್ಯಾರ್ಥಿ ಲಾಗಿನ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    tcs_cbt_title: 'TCS iON ಪರೀಕ್ಷಾ ವ್ಯವಸ್ಥೆ',
    system_no: 'ವ್ಯವಸ್ಥೆ ಸಂಖ್ಯೆ: C-004',
    candidate_name: 'ಅಭ್ಯರ್ಥಿಯ ಹೆಸರು',
    roll_no: 'ರೋಲ್ ಸಂಖ್ಯೆ',
    time_left: 'ಉಳಿದ ಸಮಯ',
    view_instructions: 'ಸೂಚನೆಗಳು',
    view_question_paper: 'ಪ್ರಶ್ನೆ ಪತ್ರಿಕೆ',
    attached_pdf: 'ಲಗತ್ತಿಸಲಾದ ಪಿಡಿಎಫ್ ಟಿಪ್ಪಣಿ',
    language: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    font_size: 'ಫಾಂಟ್ ಗಾತ್ರ',
    high_contrast: 'ಹೈ ಕಾಂಟ್ರಾಸ್ಟ್',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',
    legend_not_visited: 'ವೀಕ್ಷಿಸಿಲ್ಲ',
    legend_not_answered: 'ಉತ್ತರಿಸಿಲ್ಲ',
    legend_answered: 'ಉತ್ತರಿಸಲಾಗಿದೆ',
    legend_marked: 'ಮರುಪರಿಶೀಲನೆಗೆ ಗುರುತಿಸಲಾಗಿದೆ',
    legend_answered_marked: 'ಉತ್ತರಿಸಿ ಮರುಪರಿಶೀಲನೆಗೆ ಗುರುತಿಸಲಾಗಿದೆ (ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗುತ್ತದೆ)',
    question_palette: 'ಪ್ರಶ್ನೆ ಪ್ಯಾಲೆಟ್',
    question_no: 'ಪ್ರಶ್ನೆ ಸಂಖ್ಯೆ',
    marks: 'ಅಂಕಗಳು',
    negative_marks: 'ಋಣಾತ್ಮಕ ಅಂಕಗಳು',
    save_and_next: 'ಉಳಿಸಿ ಮುಂದಕ್ಕೆ ಹೋಗಿ',
    clear_response: 'ಉತ್ತರ ಅಳಿಸಿ',
    mark_for_review_next: 'ಮರುಪರಿಶೀಲನೆಗೆ ಗುರುತಿಸಿ ಮುಂದಕ್ಕೆ ಹೋಗಿ',
    submit_exam: 'ಪರೀಕ್ಷೆ ಸಲ್ಲಿಸಿ',
    previous: 'ಹಿಂದಿನ',
    next: 'ಮುಂದಿನ',
    choose_target_exam: 'ಗುರಿ ಪರೀಕ್ಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ:',
    targeting: 'ಗುರಿ ಪರೀಕ್ಷೆ',
    official_mocks: 'ಗಾಗಿ ಅಧಿಕೃತ ಅಣಕು ಪರೀಕ್ಷೆಗಳು',
    available_tests: 'ಲಭ್ಯವಿರುವ ಪರೀಕ್ಷೆಗಳು',
    start_test: 'ಪರೀಕ್ಷೆ ಪ್ರಾರಂಭಿಸಿ',
    unlock_pass: '₹2 ರಲ್ಲಿ ಅನ್‌ಲಾಕ್ ಮಾಡಿ',
    free_test: 'ಉಚಿತ ಪರೀಕ್ಷೆ',
    custom_segment: '10-50 ಪ್ರಶ್ನೆಗಳು',
    read_pdf_first: 'ಮೊದಲು ಪಿಡಿಎಫ್ ಓದಿ',
    all_types: 'ಎಲ್ಲಾ ಪ್ರಕಾರಗಳು',
    chapterwise: 'ಅಧ್ಯಾಯವಾರು',
    full_length: 'ಪೂರ್ಣ ಪ್ರಮಾಣದ ಮಾಕ್ಸ್',
    sectional: 'ವಿಭಾಗವಾರು',
    search_placeholder: 'ಪ್ರಶ್ನೆಗಳು, ವಿಷಯಗಳನ್ನು ಹುಡುಕಿ...',
    pass_status: 'ಪಾಸ್ ಸ್ಥಿತಿ',
    pass_active: 'ಪಾಸ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    free_trial: 'ಉಚಿತ ಪ್ರಯೋಗ',
    extend_pass: 'ಪಾಸ್ ವಿಸ್ತರಿಸಿ (365 ದಿನಗಳು)',
    unlock_full_access: '₹2 ರಲ್ಲಿ ಪೂರ್ಣ ಪ್ರವೇಶ ಪಡೆಯಿರಿ',
    mandatory_quote: 'ಕಳೆದ 5 ವರ್ಷಗಳಲ್ಲಿ ಭಾರತದಾದ್ಯಂತ 1 ಲಕ್ಷಕ್ಕೂ ಹೆಚ್ಚು ವಿದ್ಯಾರ್ಥಿಗಳು ಈ ವೇದಿಕೆಯ ಮೂಲಕ ಪರೀಕ್ಷೆಗಳಲ್ಲಿ ತೇರ್ಗಡೆಯಾಗಿದ್ದಾರೆ',
    confirm_submit_title: 'ಪರೀಕ್ಷೆಯನ್ನು ಸಲ್ಲಿಸಬೇಕೇ?',
    confirm_submit_msg: 'ನೀವು ಖಚಿತವಾಗಿ ಪರೀಕ್ಷೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲು ಬಯಸುವಿರಾ?',
    cancel: 'ರದ್ದುಮಾಡಿ',
    confirm_submit_btn: 'ಹೌದು, ಸಲ್ಲಿಸಿ',
    exam_summary: 'ಪರೀಕ್ಷೆಯ ಸಾರಾಂಶ',
    total_questions: 'ಒಟ್ಟು ಪ್ರಶ್ನೆಗಳು',
  },
  or: {
    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    mock_tests: 'ମକ୍ ଟେଷ୍ଟ',
    analytics: 'ଫଳାଫଳ ବିଶ୍ଳେଷଣ',
    notifications: 'ପରୀକ୍ଷା କ୍ୟାଲେଣ୍ଡର',
    ebooks: 'ଷ୍ଟଡି ନୋଟ୍ସ ଏବଂ ପିଡିଏଫ୍',
    teach_with_us: 'ଆମ ସହିତ ଶିକ୍ଷାଦାନ କରନ୍ତୁ',
    admin_portal: 'ଆଡମିନ୍ ପୋର୍ଟାଲ୍',
    login_with_google: 'ଛାତ୍ର ଲଗ୍ଇନ୍',
    logout: 'ଲଗ୍ଆଉଟ୍',
    tcs_cbt_title: 'TCS iON ପରୀକ୍ଷା ପ୍ରଣାଳୀ',
    system_no: 'ସିଷ୍ଟମ ନମ୍ବର: C-004',
    candidate_name: 'ପରୀକ୍ଷାର୍ଥୀଙ୍କ ନାମ',
    roll_no: 'ରୋଲ୍ ନମ୍ବର',
    time_left: 'ବାକି ସମୟ',
    view_instructions: 'ନିର୍ଦ୍ଦେଶାବଳୀ',
    view_question_paper: 'ପ୍ରଶ୍ନପତ୍ର',
    attached_pdf: 'ସଂଲଗ୍ନ ପିଡିଏଫ୍ ନୋଟ୍',
    language: 'ଭାଷା ବାଛନ୍ତୁ',
    font_size: 'ଫଣ୍ଟ ଆକାର',
    high_contrast: 'ଉଚ୍ଚ କଣ୍ଟ୍ରାଷ୍ଟ',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',
    legend_not_visited: 'ଦେଖାଯାଇ ନାହିଁ',
    legend_not_answered: 'ଉତ୍ତର ଦିଆଯାଇ ନାହିଁ',
    legend_answered: 'ଉତ୍ତର ଦିଆଯାଇଛି',
    legend_marked: 'ପୁନର୍ବିଚାର ପାଇଁ ଚିହ୍ନିତ',
    legend_answered_marked: 'ଉତ୍ତର ଦେଇ ପୁନର୍ବିଚାର ପାଇଁ ଚିହ୍ନିତ (ମୂଲ୍ୟାଙ୍କନ ହେବ)',
    question_palette: 'ପ୍ରଶ୍ନ ପ୍ୟାଲେଟ୍',
    question_no: 'ପ୍ରଶ୍ନ ନଂ',
    marks: 'ନମ୍ବର',
    negative_marks: 'ନକାରାତ୍ମକ ନମ୍ବର',
    save_and_next: 'ସଂରକ୍ଷଣ ଏବଂ ପରବର୍ତ୍ତୀ',
    clear_response: 'ଉତ୍ତର ସଫା କରନ୍ତୁ',
    mark_for_review_next: 'ପୁନର୍ବିଚାର ପାଇଁ ଚିହ୍ନିତ କରି ପରବର୍ତ୍ତୀ',
    submit_exam: 'ପରୀକ୍ଷା ଦାଖଲ କରନ୍ତୁ',
    previous: 'ପୂର୍ବବର୍ତ୍ତୀ',
    next: 'ପରବର୍ତ୍ତୀ',
    choose_target_exam: 'ଲକ୍ଷ୍ୟ ପରୀକ୍ଷା ବାଛନ୍ତୁ:',
    targeting: 'ଲକ୍ଷ୍ୟ ପରୀକ୍ଷା',
    official_mocks: 'ପାଇଁ ଅଫିସିଆଲ୍ ମକ୍ ଟେଷ୍ଟ୍',
    available_tests: 'ଉପଲବ୍ଧ ଟେଷ୍ଟ୍',
    start_test: 'ଟେଷ୍ଟ୍ ଆରମ୍ଭ କରନ୍ତୁ',
    unlock_pass: '₹୨ ରେ ଅନଲକ୍ କରନ୍ତୁ',
    free_test: 'ମାଗଣା ଟେଷ୍ଟ୍',
    custom_segment: '୧୦-୫୦ ପ୍ରଶ୍ନ',
    read_pdf_first: 'ପ୍ରଥମେ ପିଡିଏଫ୍ ପଢ଼ନ୍ତୁ',
    all_types: 'ସମସ୍ତ ପ୍ରକାର',
    chapterwise: 'ଅଧ୍ୟାୟ ଅନୁସାରେ',
    full_length: 'ସମ୍ପୂର୍ଣ୍ଣ ମକ୍ ଟେଷ୍ଟ୍',
    sectional: 'ବିଭାଗ ଅନୁସାରେ',
    search_placeholder: 'ପ୍ରଶ୍ନ, ବିଷୟ ଖୋଜନ୍ତୁ...',
    pass_status: 'ପାସ୍ ସ୍ଥିତି',
    pass_active: 'ପାସ୍ ସକ୍ରିୟ ଅଛି',
    free_trial: 'ମାଗଣା ଟ୍ରାଏଲ୍',
    extend_pass: 'ପାସ୍ ବଢ଼ାନ୍ତୁ (୩୬୫ ଦିନ)',
    unlock_full_access: '₹୨ ରେ ସମ୍ପୂର୍ଣ୍ଣ ଆକ୍ସେସ୍ ନିଅନ୍ତୁ',
    mandatory_quote: 'ଗତ ୫ ବର୍ଷରେ ସମଗ୍ର ଭାରତରେ ୧ ଲକ୍ଷରୁ ଅଧିକ ଛାତ୍ରଛାତ୍ରୀ ଏହି ପ୍ଲାଟଫର୍ମ ବ୍ୟବହାର କରି ପରୀକ୍ଷାରେ ଉତ୍ତୀର୍ଣ୍ଣ ହୋଇଛନ୍ତି',
    confirm_submit_title: 'ପରୀକ୍ଷା ଦାଖଲ କରିବାକୁ ଚାହାଁନ୍ତି କି?',
    confirm_submit_msg: 'ଆପଣ ନିଶ୍ଚିତ କି ଆପଣ ପରୀକ୍ଷା ସମାପ୍ତ କରିବାକୁ ଚାହାଁନ୍ତି?',
    cancel: 'ବାତିଲ୍ କରନ୍ତୁ',
    confirm_submit_btn: 'ହଁ, ଦାଖଲ କରନ୍ତୁ',
    exam_summary: 'ପରୀକ୍ଷା ସାରାଂଶ',
    total_questions: 'ମୋଟ ପ୍ରଶ୍ନ',
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    mock_tests: 'മോക്ക് ടെസ്റ്റുകൾ',
    analytics: 'പ്രകടന വിശകലനം',
    notifications: 'പരീക്ഷ കലണ്ടർ',
    ebooks: 'പഠന കുറിപ്പുകളും പി.ഡി.എഫും',
    teach_with_us: 'ഞങ്ങളോടൊപ്പം പഠിപ്പിക്കുക',
    admin_portal: 'അഡ്മിൻ പോർട്ടൽ',
    login_with_google: 'സ്റ്റുഡന്റ് ലോഗിൻ',
    logout: 'ലോഗൗട്ട്',
    tcs_cbt_title: 'TCS iON പരീക്ഷാ സംവിധാനം',
    system_no: 'സിസ്റ്റം നമ്പർ: C-004',
    candidate_name: 'പരീക്ഷാർത്ഥിയുടെ പേര്',
    roll_no: 'റോൾ നമ്പർ',
    time_left: 'ബാക്കി സമയം',
    view_instructions: 'നിർദ്ദേശങ്ങൾ',
    view_question_paper: 'ചോദ്യപേപ്പർ',
    attached_pdf: 'പി.ഡി.എഫ് കുറിപ്പ്',
    language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    font_size: 'ഫോണ്ട് വലുപ്പം',
    high_contrast: 'ഉയർന്ന കോൺട്രാസ്റ്റ്',
    zoom_in: 'A+',
    zoom_normal: 'A',
    zoom_out: 'A-',
    legend_not_visited: 'സന്ദർശിച്ചിട്ടില്ല',
    legend_not_answered: 'ഉത്തരം നൽകിയിട്ടില്ല',
    legend_answered: 'ഉത്തരം നൽകി',
    legend_marked: 'പുനരവലോകനത്തിനായി അടയാളപ്പെടുത്തി',
    legend_answered_marked: 'ഉത്തരം നൽകി പുനരവലോകനത്തിനായി അടയാളപ്പെടുത്തി (മൂല്യനിർണ്ണയം ചെയ്യും)',
    question_palette: 'ചോദ്യ പലക',
    question_no: 'ചോദ്യം നമ്പർ',
    marks: 'മാർക്കുകൾ',
    negative_marks: 'നെഗറ്റീവ് മാർക്ക്',
    save_and_next: 'സേവ് ചെയ്ത് അടുത്തതിലേക്ക്',
    clear_response: 'ഉത്തരം മായ്ക്കുക',
    mark_for_review_next: 'അടയാളപ്പെടുത്തി അടുത്തതിലേക്ക്',
    submit_exam: 'പരീക്ഷ സമർപ്പിക്കുക',
    previous: 'മുമ്പത്തേത്',
    next: 'അടുത്തത്',
    choose_target_exam: 'ലക്ഷ്യ പരീക്ഷ തിരഞ്ഞെടുക്കുക:',
    targeting: 'ലക്ഷ്യ പരീക്ഷ',
    official_mocks: 'നായുള്ള ഔദ്യോഗിക മോക്ക് ടെസ്റ്റുകൾ',
    available_tests: 'ലഭ്യമായ ടെസ്റ്റുകൾ',
    start_test: 'ടെസ്റ്റ് ആരംഭിക്കുക',
    unlock_pass: '₹2 ൽ അൺലോക്ക് ചെയ്യുക',
    free_test: 'സൗജന്യ ടെസ്റ്റ്',
    custom_segment: '10-50 ചോദ്യങ്ങൾ',
    read_pdf_first: 'ആദ്യം പി.ഡി.എഫ് വായിക്കുക',
    all_types: 'എല്ലാ തരങ്ങളും',
    chapterwise: 'അധ്യായം തിരിച്ച്',
    full_length: 'പൂർണ്ണ മോക്ക് ടെസ്റ്റുകൾ',
    sectional: 'വിഭാഗം തിരിച്ച്',
    search_placeholder: 'ചോദ്യങ്ങൾ, വിഷയങ്ങൾ തിരയുക...',
    pass_status: 'പാസ് നില',
    pass_active: 'പാസ് സജീവമാണ്',
    free_trial: 'സൗജന്യ ട്രയൽ',
    extend_pass: 'പാസ് നീട്ടുക (365 ദിവസം)',
    unlock_full_access: '₹2 ൽ പൂർണ്ണ ആക്സസ് നേടുക',
    mandatory_quote: 'കഴിഞ്ഞ 5 വർഷത്തിനിടയിൽ ഇന്ത്യയിലുടനീളം 1 ലക്ഷത്തിലധികം വിദ്യാർത്ഥികൾ ഈ പ്ലാറ്റ്‌ഫോം വഴി വിജയിച്ചു',
    confirm_submit_title: 'പരീക്ഷ സമർപ്പിക്കണോ?',
    confirm_submit_msg: 'ഈ ടെസ്റ്റ് അവസാനിപ്പിച്ച് സമർപ്പിക്കണമെന്ന് ഉറപ്പാണോ?',
    cancel: 'റദ്ദാക്കുക',
    confirm_submit_btn: 'അതെ, സമർപ്പിക്കുക',
    exam_summary: 'പരീക്ഷാ സംഗ്രഹം',
    total_questions: 'ആകെ ചോദ്യങ്ങൾ',
  }
};

/**
 * Question Translations helper for 10 languages
 */
// Database of translations across 10 Indian Languages for core questions
export const QUESTION_TRANSLATIONS_DB: Record<string, Partial<Record<LanguageCode, { questionText: string; options?: string[]; explanation?: string }>>> = {
  'q-cgl-01': {
    hi: {
      questionText: 'उस विकल्प का चयन करें जो तीसरे अक्षर-समूह से उसी प्रकार संबंधित है जैसे दूसरा अक्षर-समूह पहले अक्षर-समूह से संबंधित है:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'प्रत्येक अक्षर को वर्णमाला के उसके विपरीत अक्षर से बदला गया है (विपरीत अक्षरों के स्थानों का योग = 27)। अतः सही उत्तर QOMK है।'
    },
    bn: {
      questionText: 'এমন বিকল্পটি নির্বাচন করুন যা তৃতীয় অক্ষর-গুচ্ছের সাথে ঠিক একইভাবে সম্পর্কিত যেভাবে দ্বিতীয় অক্ষর-গুচ্ছটি প্রথমটির সাথে সম্পর্কিত:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'প্রতিটি অক্ষরকে বিপরীত অক্ষর দ্বারা প্রতিস্থাপন করা হয়েছে (স্থানের যোগফল = ২৭)। উত্তর: QOMK।'
    },
    te: {
      questionText: 'మొదటి అక్షర సమూహంతో రెండవది ఎలా సంబంధం కలిగి ఉందో, మూడవదానితో అదే విధంగా సంబంధం ఉన్న సరైన ఎంపికను ఎంచుకోండి:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'ప్రతి అక్షరం వర్ణమాలలో దాని వ్యతిరేక అక్షరంతో భర్తీ చేయబడింది (మొత్తం = 27). సమాధానం: QOMK.'
    },
    mr: {
      questionText: 'त्या पर्यायाची निवड करा ज्याचा तिसऱ्या अक्षर-गटाशी तसाच संबंध आहे जसा दुसऱ्या गटाचा पहिल्याशी आहे:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'प्रत्येक अक्षर त्याच्या विरुद्ध अक्षराने बदलले आहे (बेरीज = २७). उत्तर: QOMK.'
    },
    ta: {
      questionText: 'முதல் எழுத்துத் தொகுதிக்கு இரண்டாவது தொகுதி எவ்வாறு தொடர்புடையதோ, அதேபோல் மூன்றாவது தொகுதிக்குத் தொடர்புடைய விருப்பத்தைத் தேர்ந்தெடுக்கவும்:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'ஒவ்வொரு எழுத்தும் அதன் எதிர் எழுத்தால் மாற்றப்பட்டுள்ளது (கூடுதல் = 27). விடை: QOMK.'
    },
    gu: {
      questionText: 'તે વિકલ્પ પસંદ કરો જે ત્રીજા અક્ષર-જૂથ સાથે તે જ રીતે સંબંધિત છે જેમ બીજું અક્ષર-જૂથ પહેલા સાથે સંબંધિત છે:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'દરેક અક્ષર તેના વિરુદ્ધ અક્ષરથી બદલવામાં આવ્યો છે (સરવાળો = 27). જવાબ: QOMK.'
    },
    kn: {
      questionText: 'ಮೊದಲ ಅಕ್ಷರ ಗುಂಪಿಗೆ ಎರಡನೆಯದು ಹೇಗೆ ಸಂಬಂಧಿಸಿದೆಯೋ, ಹಾಗೆಯೇ ಮೂರನೆಯ ಗುಂಪಿಗೆ ಸಂಬಂಧಿಸಿದ ಸರಿಯಾದ ಆಯ್ಕೆಯನ್ನು ಆರಿಸಿ:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'ಪ್ರತಿ ಅಕ್ಷರವನ್ನು ವಿರುದ್ಧ ಅಕ್ಷರದಿಂದ ಬದಲಾಯಿಸಲಾಗಿದೆ (ಮೊತ್ತ = 27). ಉತ್ತರ: QOMK.'
    },
    or: {
      questionText: 'ସେହି ବିକଳ୍ପ ଚୟନ କରନ୍ତୁ ଯାହା ତୃତୀୟ ଅକ୍ଷର-ଗୋଷ୍ଠୀ ସହିତ ସମାନ ଭାବରେ ସମ୍ପର୍କିତ ଯେପରି ଦ୍ୱିତୀୟଟି ପ୍ରଥମ ସହିତ ସମ୍ପର୍କିତ:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'ପ୍ରତ୍ୟେକ ଅକ୍ଷର ବିପରୀତ ଅକ୍ଷର ଦ୍ୱାରା ପ୍ରତିସ୍ଥାପିତ (ଯୋଗଫଳ = ୨୭)। ଉତ୍ତର: QOMK।'
    },
    ml: {
      questionText: 'ആദ്യ അക്ഷരക്കൂട്ടവുമായി രണ്ടാമത്തേത് എങ്ങനെ ബന്ധപ്പെട്ടിരിക്കുന്നുവോ, അതുപോലെ മൂന്നാമത്തേതുമായി ബന്ധപ്പെട്ട ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക:\nBDFH : YWUS :: JLNP : ?',
      options: ['QOMK', 'SQOM', 'TRPN', 'VTRP'],
      explanation: 'ഓരോ അക്ഷരവും വിപരീത അക്ഷരം കൊണ്ട് മാറ്റിസ്ഥാപിച്ചിരിക്കുന്നു (തുക = 27). ഉത്തരം: QOMK.'
    }
  },
  'q-cgl-02': {
    hi: {
      questionText: 'निम्नलिखित श्रृंखला में प्रश्न चिह्न (?) के स्थान पर कौन सी संख्या आएगी?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'अंतर: 4 (2²), 9 (3²), 16 (4²), 25 (5²)। अगला अंतर 6² = 36 होगा। 61 + 36 = 97।'
    },
    bn: {
      questionText: 'নিম্নলিখিত সংখ্যা-ধারায় প্রশ্নবোধক চিহ্নে (?) কোন সংখ্যাটি বসবে?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'পার্থক্য: 4 (2²), 9 (3²), 16 (4²), 25 (5²)। পরবর্তী পার্থক্য 6² = 36। অতএব 61 + 36 = 97।'
    },
    te: {
      questionText: 'క్రింది శ్రేణిలో ప్రశ్న గుర్తు (?) స్థానంలో ఏ సంఖ్య వస్తుంది?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'తేడాలు: 4 (2²), 9 (3²), 16 (4²), 25 (5²). తదుపరి తేడా = 36. 61 + 36 = 97.'
    },
    mr: {
      questionText: 'खालील मालिकेतील प्रश्नचिन्हाच्या (?) जागी कोणती संख्या येईल?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'फरक: 4 (2²), 9 (3²), 16 (4²), 25 (5²). पुढील फरक 36 असेल. 61 + 36 = 97.'
    },
    ta: {
      questionText: 'பின்வரும் தொடரில் கேள்விக்குறி (?) இடத்திற்கு வரும் எண் எது?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'வித்தியாசம்: 4 (2²), 9 (3²), 16 (4²), 25 (5²). அடுத்த வித்தியாசம் 36. 61 + 36 = 97.'
    },
    gu: {
      questionText: 'નીચેની શ્રેણીમાં પ્રશ્નાર્થ ચિહ્ન (?) ની જગ્યાએ કઈ સંખ્યા આવશે?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'તફાવત: 4 (2²), 9 (3²), 16 (4²), 25 (5²). હવે પછીનો તફાવત 36. 61 + 36 = 97.'
    },
    kn: {
      questionText: 'ಕೆಳಗಿನ ಸರಣಿಯಲ್ಲಿ ಪ್ರಶ್ನಾರ್ಥಕ ಚಿಹ್ನೆಯ (?) ಸ್ಥಳದಲ್ಲಿ ಯಾವ ಸಂಖ್ಯೆ ಬರುತ್ತದೆ?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'ವ್ಯತ್ಯಾಸ: 4 (2²), 9 (3²), 16 (4²), 25 (5²). ಮುಂದಿನ ವ್ಯತ್ಯಾಸ 36. 61 + 36 = 97.'
    },
    or: {
      questionText: 'ନିମ୍ନଲିଖିତ ଶ୍ରେଣୀରେ ପ୍ରଶ୍ନବାଚକ ଚିହ୍ନ (?) ସ୍ଥାନରେ କେଉଁ ସଂଖ୍ୟା ଆସିବ?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'ପାର୍ଥକ୍ୟ: ୪ (୨²), ୯ (୩²), ୧୬ (୪²), ୨୫ (୫²)। ପରବର୍ତ୍ତୀ ପାର୍ଥକ୍ୟ ୩୬। ୬୧ + ୩୬ = ୯୭।'
    },
    ml: {
      questionText: 'താഴെ നൽകിയിരിക്കുന്ന ശ്രേണിയിൽ ചോദ്യചിഹ്നത്തിന് (?) പകരം വരുന്ന സംഖ്യ ഏതാണ്?\n7, 11, 20, 36, 61, ?',
      options: ['93', '97', '102', '89'],
      explanation: 'വ്യത്യാസം: 4 (2²), 9 (3²), 16 (4²), 25 (5²). അടുത്ത വ്യത്യാസം 36. 61 + 36 = 97.'
    }
  },
  'q-cgl-04': {
    hi: {
      questionText: 'भारतीय संविधान का कौन सा अनुच्छेद "जीवन और व्यक्तिगत स्वतंत्रता का संरक्षण" प्रदान करता है?',
      options: ['अनुच्छेद 19', 'अनुच्छेद 21', 'अनुच्छेद 14', 'अनुच्छेद 32'],
      explanation: 'अनुच्छेद 21 घोषित करता है कि कानून द्वारा स्थापित प्रक्रिया के अतिरिक्त किसी भी व्यक्ति को उसके जीवन या व्यक्तिगत स्वतंत्रता से वंचित नहीं किया जाएगा।'
    },
    bn: {
      questionText: 'ভারতীয় সংবিধানের কোন অনুচ্ছেদটি "জীবন ও ব্যক্তিগত স্বাধীনতার সুরক্ষা" প্রদান করে?',
      options: ['অনুচ্ছেদ ১৯', 'অনুচ্ছেদ ২১', 'অনুচ্ছেদ ১৪', 'অনুচ্ছেদ ৩২'],
      explanation: 'অনুচ্ছেদ ২১ অনুযায়ী আইনের দ্বারা নির্ধারিত পদ্ধতি ছাড়া কোনো ব্যক্তিকে তার জীবন বা ব্যক্তিগত স্বাধীনতা থেকে বঞ্চিত করা যাবে না।'
    },
    te: {
      questionText: 'భారత రాజ్యాంగంలోని ఏ అధికరణ "జీవించే హక్కు మరియు వ్యక్తిగత స్వేచ్ఛ రక్షణ"ను అందిస్తుంది?',
      options: ['అధికరణ 19', 'అధికరణ 21', 'అధికరణ 14', 'అధికరణ 32'],
      explanation: 'ఆర్టికల్ 21 చట్టం నిర్దేశించిన పద్ధతి ప్రకారం తప్ప ఏ వ్యక్తి జీవితాన్ని లేదా వ్యక్తిగత స్వేచ్ఛను హరించరాదని పేర్కొంటుంది.'
    },
    mr: {
      questionText: 'भारतीय संविधानाचे कोणते कलम "जीवनाचे व वैयक्तिक स्वातंत्र्याचे रक्षण" प्रदान करते?',
      options: ['कलम १९', 'कलम २१', 'कलम १४', 'कलम ३२'],
      explanation: 'कलम २१ कायद्याने प्रस्थापित केलेली कार्यपद्धती वगळता कोणालाही त्याच्या जगण्याच्या किंवा व्यक्तिगत स्वातंत्र्यापासून वंचित केले जाणार नाही.'
    },
    ta: {
      questionText: 'இந்திய அரசியலமைப்பின் எந்தப் பிரிவு "வாழ்வுரிமை மற்றும் தனிநபர் சுதந்திரப் பாதுகாப்பை" வழங்குகிறது?',
      options: ['பிரிவு 19', 'பிரிவு 21', 'பிரிவு 14', 'பிரிவு 32'],
      explanation: 'சட்டத்தால் நிறுவப்பட்ட நடைமுறையின்றி எவரது வாழ்வுரிமையும் தனிநபர் சுதந்திரமும் பறிக்கப்படக் கூடாது என பிரிவு 21 கூறுகிறது.'
    },
    gu: {
      questionText: 'ભારતીય બંધારણની કઈ કલમ "જીવન અને વ્યક્તિગત સ્વતંત્રતાનું રક્ષણ" આપે છે?',
      options: ['કલમ 19', 'કલમ 21', 'કલમ 14', 'કલમ 32'],
      explanation: 'કલમ 21 કાયદા દ્વારા સ્થાપિત પ્રક્રિયા સિવાય કોઈપણ વ્યક્તિને તેના જીવન કે વ્યક્તિગત સ્વતંત્રતાથી વંચિત નહીં કરી શકાય.'
    },
    kn: {
      questionText: 'ಭಾರತೀಯ ಸಂವಿಧಾನದ ಯಾವ ವಿಧಿಯು "ಜೀವನ ಮತ್ತು ವೈಯಕ್ತಿಕ ಸ್ವಾತಂತ್ರ್ಯದ ರಕ್ಷಣೆ"ಯನ್ನು ನೀಡುತ್ತದೆ?',
      options: ['ವಿಧಿ 19', 'ವಿಧಿ 21', 'ವಿಧಿ 14', 'ವಿಧಿ 32'],
      explanation: 'ವಿಧಿ 21 ಕಾನೂನುಬದ್ಧ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಹೊರತುಪಡಿಸಿ ಯಾರೊಬ್ಬರ ಜೀವನ ಅಥವಾ ವೈಯಕ್ತಿಕ ಸ್ವಾತಂತ್ರ್ಯವನ್ನು ಕಸಿದುಕೊಳ್ಳಲಾಗುವುದಿಲ್ಲ ಎಂದು ಹೇಳುತ್ತದೆ.'
    },
    or: {
      questionText: 'ଭାରତୀୟ ସମ୍ବିଧାନର କେଉଁ ଧାରା "ଜୀବନ ଓ ବ୍ୟକ୍ତିଗତ ସ୍ୱାଧୀନତାର ସୁରକ୍ଷା" ପ୍ରଦାନ କରେ?',
      options: ['ଧାରା ୧୯', 'ଧାରା ୨୧', 'ଧାରା ୧୪', 'ଧାରା ୩୨'],
      explanation: 'ଧାରା ୨୧ କହେ ଯେ ଆଇନ ଦ୍ୱାରା ପ୍ରତିଷ୍ଠିତ ପ୍ରକ୍ରିୟା ବିନା କୌଣସି ବ୍ୟକ୍ତିଙ୍କୁ ଜୀବନ ବା ବ୍ୟକ୍ତିଗତ ସ୍ୱାଧୀନତାରୁ ବଞ୍ଚିତ କରାଯିବ ନାହିଁ।'
    },
    ml: {
      questionText: 'ഇന്ത്യൻ ഭരണഘടനയുടെ ഏത് വകുപ്പാണ് "ജീവനും വ്യക്തിസ്വാതന്ത്ര്യത്തിനുമുള്ള സംരക്ഷണം" ഉറപ്പുനൽകുന്നത്?',
      options: ['വകുപ്പ് 19', 'വകുപ്പ് 21', 'വകുപ്പ് 14', 'വകുപ്പ് 32'],
      explanation: 'നിയമപരമായ നടപടിക്രമങ്ങളിലൂടെയല്ലാതെ ആർക്കും ജീവനോ വ്യക്തിസ്വാതന്ത്ര്യമോ നഷ്ടപ്പെടരുത് എന്ന് ആർട്ടിക്കിൾ 21 ഉറപ്പുനൽകുന്നു.'
    }
  }
};

/**
 * Question Translations helper for 10 languages
 */
export const getLocalizedQuestion = (
  q: any,
  lang: LanguageCode
): { questionText: string; options: string[]; explanation: string } => {
  if (!q) {
    return { questionText: '', options: [], explanation: '' };
  }

  // 1. Check direct translation in question object
  if (q.translations && q.translations[lang]) {
    return {
      questionText: q.translations[lang].questionText || q.questionText,
      options: q.translations[lang].options || q.options,
      explanation: q.translations[lang].explanation || q.explanation
    };
  }

  // 2. Check global QUESTION_TRANSLATIONS_DB for this question id
  if (q.id && QUESTION_TRANSLATIONS_DB[q.id] && QUESTION_TRANSLATIONS_DB[q.id][lang]) {
    const dbItem = QUESTION_TRANSLATIONS_DB[q.id][lang]!;
    return {
      questionText: dbItem.questionText || q.questionText,
      options: dbItem.options || q.options,
      explanation: dbItem.explanation || q.explanation
    };
  }

  // 3. If Hindi requested and legacy questionTextHindi exists
  if (lang === 'hi' && q.questionTextHindi) {
    return {
      questionText: q.questionTextHindi,
      options: q.optionsHindi && q.optionsHindi.length > 0 ? q.optionsHindi : q.options,
      explanation: q.explanationHindi || q.explanation
    };
  }

  // 4. Default fallback to English
  return {
    questionText: q.questionText,
    options: q.options,
    explanation: q.explanation
  };
};
